### ISSUE TITLE
Infrastructure Scoreboard Setup

### ISSUE THREAD

**Issue by jeffg2k** [google/google-ctf#55]
I'm trying to run the infrastructure on Firebase as described in the [Readme](https://github.com/google/google-ctf/blob/master/infrastructure/scoreboard/README.md), but I'm getting a `goog is not defined` from the `goog.module()` declarations.  I don't know enough about Node (Python guy) to understand how this is suppose to work.  Any help would be appreciated. 

```
beginners.js:20 Uncaught ReferenceError: goog is not defined
    at beginners.js:20
(anonymous) @ beginners.js:20
database.js:5 Uncaught ReferenceError: goog is not defined
    at database.js:5
(anonymous) @ database.js:5
readme.js:5 Uncaught ReferenceError: goog is not defined
    at readme.js:5
(anonymous) @ readme.js:5
session.js:5 Uncaught ReferenceError: goog is not defined
    at session.js:5
(anonymous) @ session.js:5
tasklist.js:5 Uncaught ReferenceError: goog is not defined
    at tasklist.js:5
(anonymous) @ tasklist.js:5
teamlist.js:5 Uncaught ReferenceError: goog is not defined
    at teamlist.js:5
(anonymous) @ teamlist.js:5
theme.js:6 Uncaught ReferenceError: goog is not defined
    at theme.js:6
(anonymous) @ theme.js:6
ui.js:5 Uncaught ReferenceError: goog is not defined
    at ui.js:5
(anonymous) @ ui.js:5
scoreboard.js:1 Uncaught SyntaxError: Identifier 'Beginners' has already been declared
bootstrap.js:5 Uncaught ReferenceError: goog is not defined
    at bootstrap.js:5
```

I took the extra step of adding `npm install googl` and `npm install google-closure-library` to the dependency, but that didn't fix it.  I tried to define it using `const goog = require('goog');` as described when adding [Firebase Dependencies](https://firebase.google.com/docs/functions/handle-dependencies), but no luck.  Now it just says `require is not defined`

**Comment by jeffg2k** [comment]
I was able to get past this issue by removing all the goog stuff as I don't think it was really needed, except where variables were defined, which I just changed to constants.  For example:
```
/** @define {string} API Key for CTF scoreboard */
const API_KEY = '';
/** @define {string} Auth Domain for CTF scoreboard */
const AUTH_DOMAIN = '';
/** @define {string} Database URL for CTF scoreboard */
const DATABASE_URL = '';
/** @define {string} Project ID for CTF scoreboard */
const PROJECT_ID = '';
/** @define {string} Storage Bucket for CTF scoreboard */
const STORAGE_BUCKET = '';
```
I'm still not sure how challenges are loaded, how teams are created or anything else.  So any more info would be great.

**Comment by jeffg2k** [comment]
As a note for an additional step, I got authentication working.  It requires that you go into Firebase Authentication and Enable Google Authentication Provider.  I don't show up on the "Teams", but one step at a time.  Still trying to figure out how load challenges.

**Comment by eljeffeg** [comment]
As a note for anyone looking, I published a working update to the Infrastructure code.  Since I made so many changes for my own use, I wasn't sure about a PR to this repo.  Instead, I just created a new one and figured I'd post here.  Feel free to grab the needed diff changes into this repo if you like. https://github.com/eljeffeg/SynthwaveCTF
